Repository iotaledger/iota.js, pull requests merged in 2018-05, with the labels that each got.

#220 Fixes for batched send
  lib/utils/makeRequest.js
  test/utils/utils.batchedSend.js
Labels: P2 - High

#214 Update readme to refer to storeAndBroadcast instead of broadcastAndStore
  README.md
Labels: docs

#215 Update multisig section in readme
  README.md
Labels: docs

#206 v0.4.8
  bower.json
  dist/iota.js
  dist/iota.js.map
  dist/iota.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: P2 - High, enhancement

#221 Support for remote authentication
  lib/iota.js
  lib/utils/makeRequest.js
Labels: enhancement
